# @package _global_

# specify here default evaluation configuration
defaults:
  - _self_
  - datamodule: colon2.yaml # choose the datamodule for evaluation
  - model: voting.yaml   # voting.yaml   newvote.yaml   savefeatures.yaml newvote_probability.yaml
  - callbacks: test.yaml
  - logger: wandb.yaml   # none.yaml    wandb
  - trainer: gpu.yaml
  - log_dir: evaluation.yaml

  - experiment: null

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

original_work_dir: ${hydra:runtime.cwd}

data_dir: ${original_work_dir}/data/

print_config: True

ignore_warnings: True

seed: 42

name: "default"

# passing checkpoint path is necessary
ckpt_path: "/home/compu/LJC/colon_compare/scripts/scripts/logs/experiments/runs/colon/classifycompare/vit_base_r50_s16_384/2023-05-08_06-33-38/checkpoints/epoch_022.ckpt"